### PR TITLE
Added getPixelAspectRatio() method and test for it.

### PR DESCRIPTION
**Pull request by SakhDelphi**

### CODE REVIEW

**Comment by char0n** [comment]
In your commit I guess you are using spaces instead of tabs. CodeStyle for this project is using tabs. If you correct this, I will be happy to merge.

**Comment by Delphi90** [comment]
Excuse me, but in most lines of your code I see spaces instead of tabs. And only a few lines you use tabs.

**Comment by char0n** [comment]
Yes you are right, I would better reformat the entire project after merging your pull request. Anyway thanks again for pull request. I'll merge as soon as I find some spare time.

**Comment by char0n** [comment]
Thanks for the PR

**Pull request merged**
