### PR TITLE
chore(release): cut the 3.1.0 release

### PR DESCRIPTION
**Pull request by char0n**

### CODE REVIEW

**Comment by ivoba** [comment]
@char0n Thanks for the new release.
Can you push it to packagist, pls:
> This package is not auto-updated.

**Comment by char0n** [comment]
@ivoba I thought I did. I clicked "Update" button and I can see 3.1.0 release there now: https://packagist.org/packages/char0n/ffmpeg-php#3.1.0

image

**Comment by ivoba** [comment]
@char0n sorry i was looking at: https://packagist.org/packages/codescale/ffmpeg-php
with char0n/ffmpeg-php it works now. thx.

**Comment by char0n** [comment]
yeah `char0n/ffmpeg-php` is primary. `codescale/ffmpeg-php` is legacy and shouldn't be used anymore. But updated that one too anyway. THanks !

**Pull request merged**
